#!/bin/bash

set -e

if [ -n "$APP_PORT" ]
then
	echo "Configuring Kafka Connect with APP_PORT: $APP_PORT"
	DOCKER_MIRROR_HOST=$(/sbin/ip route|awk '/default/ { print $3 }')
	DOCKER_MIRROR_PORT=${MIRROR_PORT:-9001}
	DOCKER_MIRROR="http://$DOCKER_MIRROR_HOST:$DOCKER_MIRROR_PORT"

	export HOST_IP=$(curl $DOCKER_MIRROR/hostip)
	export HOST_PORT=$(curl $DOCKER_MIRROR/container/$HOSTNAME/port/$APP_PORT)
	export CONNECT_REST_ADVERTISED_HOST_NAME=$HOST_IP
	export CONNECT_REST_ADVERTISED_PORT=$HOST_PORT
else
	export CONNECT_REST_ADVERTISED_HOST_NAME=$APP_HOST
	export CONNECT_REST_ADVERTISED_PORT=${CONNECT_REST_ADVERTISED_PORT:-8083}
fi

echo "CONNECT_REST_ADVERTISED_HOST_NAME: $CONNECT_REST_ADVERTISED_HOST_NAME"
echo "CONNECT_REST_ADVERTISED_PORT: $CONNECT_REST_ADVERTISED_PORT"

if [ -n "${KAFKA_JMX_PORT}" ] || [ -n "${KAFKA_JMX_HOSTNAME}" ] || [ -n "${KAFKA_JMX_OPTS}" ];
then
    # JMX agent complains about malformed URLs and is not able to resolve ECS container
    # short hostnames. This will take care of the problem.
    echo "127.0.0.1     $HOSTNAME" | tee -a /etc/hosts
fi
echo "KAFKA_JMX_HOSTNAME: ${KAFKA_JMX_HOSTNAME}"
echo "KAFKA_JMX_PORT: ${KAFKA_JMX_PORT}"

if [ -n "${CONNECT_SSL_DIR}" ];
then
  # If SSL directory env variable is set, generate keystore and truststore
  if [ ! -f ${CONNECT_SSL_DIR}/kafka.client.truststore.jks ];
  then
    # If truststore doesn't exist, generate truststore
    echo "Generating Truststore..."
    keytool -import -alias ca -file ${CONNECT_SSL_DIR}/ca.crt \
        -keystore ${CONNECT_SSL_DIR}/kafka.client.truststore.jks \
        -storepass ${CONNECT_SSL_TRUSTSTORE_PASSWORD} \
        -noprompt
    keytool -import -alias client -file ${CONNECT_SSL_DIR}/client.crt \
        -keystore ${CONNECT_SSL_DIR}/kafka.client.truststore.jks \
        -storepass ${CONNECT_SSL_TRUSTSTORE_PASSWORD} \
        -noprompt
  fi

  if [ ! -f ${CONNECT_SSL_DIR}/kafka.client.keystore.jks ];
  then
    # IF keystore doesn't exist, generate keystore
    echo "Generating Keystore..."
    keytool -importkeystore \
        -deststorepass ${CONNECT_SSL_KEYSTORE_PASSWORD} \
        -destkeypass ${CONNECT_SSL_KEY_PASSWORD} \
        -destkeystore ${CONNECT_SSL_DIR}/kafka.client.keystore.jks \
        -srckeystore ${CONNECT_SSL_DIR}/client.p12 \
        -srcstoretype PKCS12 \
        -srcstorepass ${CLIENT_KEY_PASS} \
        -alias client
  fi
fi

exec "$@"
