#!/bin/bash -e

[[ "${DEBUG}" == 'true' ]] && set -o xtrace

prg=$0
function usage() {
    echo "Usage:"
    echo "  $prg <docker repo> <image name> <version>"
}

docker_repo=$1
if [[ -z "${docker_repo}" ]]; then
    echo "Please specify the docker repo."
    usage
    exit 1
fi
shift

image_name=$1
if [[ -z "${image_name}" ]]; then
    echo "Please specify the image name."
    usage
    exit 1
fi
shift

version=$1
if [[ -z "${version}" ]]; then
    echo "Please specify the image version to tag with."
    usage
    exit 1
fi
shift

pushd ${image_name}
if [[ "${image_name}" == "jmxtrans" ]]; then
    docker build -t ${docker_repo}/${image_name}:${version} --build-arg JMXTRANS_VERSION=270 .
else
    docker build -t ${docker_repo}/${image_name}:${version} .
fi
docker push ${docker_repo}/${image_name}:${version}
popd
