#!/bin/bash -e

[[ "${DEBUG}" == 'true' ]] && set -o xtrace

prg=$0
function usage() {
    echo "Usage:"
    echo "  $prg <docker repo> <image name> <version>"
}

docker_repo=$1
shift
if [[ -z "${docker_repo}" ]]; then
    echo "Please specify the docker repo."
    usage
    exit 1
fi

image_name=$1
shift
if [[ -z "${image_name}" ]]; then
    echo "Please specify the image name."
    usage
    exit 1
fi

version=$1
shift
if [[ -z "${version}" ]]; then
    echo "Please specify the image version to tag with."
    usage
    exit 1
fi

pushd ${image_name}
docker build . -t ${docker_repo}/${image_name}:${version}
docker push ${docker_repo}/${image_name}:${version}
popd
