version: 0.2

env:
  variables:
    TEMPLATE_BUCKET: "dev-kafka-artifacts"

phases:
  install:
    commands:
      - gem install cfn-nag
      - apt-get update -y
      - apt-get install -y jq

  build:
    commands:
      - |
        CFNS=$(grep --include="*.yaml" --exclude=master.yaml --exclude=services.yaml --exclude-dir={.idea,kafka-connect,kafka-rest,schema-registry,cassandra,jmxtrans} -rnwl . -e 'AWSTemplateFormatVersion')
        for cfn in ${CFNS}; do
            echo "Validating template ${cfn}"
            ERRORS=$(aws cloudformation validate-template --template-body file://${cfn}  | jq .Error)
            if [ "${ERRORS}" != "null" ]; then
                echo "${cfn} has errors: ${ERRORS}" && exit 1
            fi
            
            echo "Running CFN_NAG scan for ${cfn}"
            cfn_nag_scan --input-path ${cfn}
            SCAN_ERRORS=$(cfn_nag_scan --input-path ${cfn} --output-format json | jq .[0].file_results.failure_count)
            if [ ${SCAN_ERRORS} != 0 ]; then
              echo "${cfn} has failures - exiting build" && exit 1
            fi
        done

  post_build:
    commands:
      - echo "Packaging master template"
      - aws cloudformation package --template-file master-template.yaml
        --s3-bucket $TEMPLATE_BUCKET --s3-prefix kafka --force-upload
        --output-template-file master.yaml

artifacts:
  files:
    - ./master.yaml
