#!/usr/bin/env bash

#set -o errexit
#set -o pipefail
[[ "${DEBUG}" == 'true' ]] && set -o xtrace

stack_suffix=$1
if [[ -z "${stack_suffix}" ]]; then
    echo "No stack suffix provided."
    stack_suffix=kafka-services
fi
echo "Using stack_suffix='${stack_suffix}'"

readonly CFNS=$(grep \
    --include="*.yaml" \
    --exclude=master-template.yaml \
    --exclude=master.yaml \
    --exclude=services.yaml \
    --exclude=ecs.yaml \
    --exclude-dir={.idea,kafka-connect,kafka-rest,schema-registry,jmxtrans} \
    -rnwl . -e 'AWSTemplateFormatVersion')

for cfn in ${CFNS}; do
    echo "Validating template ${cfn}"
    ERRORS=$(aws cloudformation validate-template --template-body file://${cfn} | jq .Error)

    if [ "${ERRORS}" != "null" ]; then
        echo "${cfn} has errors: ${ERRORS}" && exit 1
    fi
done

echo "Packaging services template"
aws cloudformation package --template-file services-template.yaml \
    --s3-bucket loyaltyone-"${ENV:-dev}"-infra --s3-prefix kafka --force-upload \
    --output-template-file services.yaml

echo "Deploying services template"
params=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)")|.[]' ../kafka-infra-config/dev-services-params.json | tr '\n' ' ')
aws cloudformation deploy --template-file services.yaml --stack-name "${ENV:-dev}"-${stack_suffix} \
    --capabilities CAPABILITY_IAM --parameter-overrides $params

# aws cloudformation describe-stack-events --stack-name "${ENV:-dev}"-${stack_suffix} --output table

echo "Cleaning up"
rm -rf services.yaml

echo "Deployed stack successfully"
