---
AWSTemplateFormatVersion: '2010-09-09'

Description: Creates an EBS volumes

Parameters:
  DataVolumeSize:
    Description: Data volume size in GB for ECS instances. These will be exposed via EBSMountPath to containers.
    Type: Number
    MinValue: 25
    MaxValue: 2000
    Default: 100
    ConstraintDescription: Must be a value between 25 and 1000
  DataVolumeType:
    Type: String
    Default: gp2
    Description: The data volume type
    AllowedValues: [gp2, io1, standard]
    ConstraintDescription: Must be a valid volume type
  DataVolumeIOPS:
    Type: String
    AllowedPattern: '[0-9]*'
    Description: For 'io1' data volumes, select number of IOPS.
    ConstraintDescription: Must be a valid IOPS value or empty
  AvailabilityZone:
    Type: String
    Description: The availability zone in which to create the EBS volume
  Project:
    Description: Project tag
    Type: String
    MinLength: 1
  Team:
    Description: Team tag
    Type: String
    MinLength: 1
  Environment:
    Description: Environment (dev|sandbox|prod)
    Type: String
    AllowedValues: ['dev','sandbox','prod']
    Default: dev
  VolumeNameTag:
    Type: String
    Description: Tag for identifying the component the volume should be tagged with
Conditions:
  UseIO1DataVolume: !Equals [!Ref DataVolumeType, 'io1']

Resources:
  DataVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref DataVolumeSize
      VolumeType: !Ref DataVolumeType
      Iops: !If [UseIO1DataVolume, !Ref DataVolumeIOPS, '']
      AvailabilityZone: !Ref AvailabilityZone
      Encrypted: true
      Tags:
        - Key: Name
          Value: !Ref 'VolumeNameTag'
        - Key: Project
          Value: !Ref 'Project'
        - Key: Team
          Value: !Ref 'Team'
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: Component
          Value: ebs
