#!/usr/bin/env bash

prg=$0

function usage() {
    echo "Usage:"
    echo "    $prg <stack name> [create|update] [dev|sandbox|prod] [components|kafka]"
}

stack_name=$1
if [[ -z ${stack_name} ]]; then
    echo "ERROR: Please specify the stack name"
    usage
    exit 1
fi

action=$2
if [[ -z ${action} ]]; then
    action=create
fi

env=$3
if [[ -z ${env} ]]; then
    env=dev
fi

cluster_type=$4
if [[ -z ${cluster_type} ]]; then
    cluster_type=components
fi

aws cloudformation ${action}-stack --capabilities CAPABILITY_IAM \
    --stack-name ${stack_name} --template-body file://ecs.yaml \
    --parameters file://../kafka-infra-config/ecs-cluster-${cluster_type}/${env}.json

echo "Stack ${action} done. Please see CloudFormation for status on your stack."

