---
AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template deploys a highly available ECS cluster using an AutoScaling Group, with
  ECS hosts distributed across multiple Availability Zones. It then deploys a Zookeeper
  cluster from containers published in Docker Hub.

Parameters:
  EfsStackName:
    Description: CloudFormation Stack Name for EFS
    Type: String
  HostedZoneStackName:
    Description: The Stack Name of the hosted zone in which to register services
    Type: String
  KeyName:
    Description: Key Pair name for SSH access
    Type: AWS::EC2::KeyPair::KeyName
  VPCId:
    Description: Choose which VPC this cluster should be deployed to
    Type: AWS::EC2::VPC::Id
  VPCCidrBlock:
    Description: VPC CIDR Block
    Type: String
  Subnets:
    Description: Choose three private subnets this cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    Description: Which instance type should we use to build the ECS cluster?
    ConstraintDescription: Must be a valid EC2 instance type
    Type: String
    AllowedValues: [r4.xlarge]
    Default: r4.xlarge
  EFSMountPath:
    Description: Path at which to create the volume mount for EFS
    Type: String
    Default: /mnt/efs
  ASGMinSize:
    Description: Minimum size of ECS Auto Scaling Group
    Type: Number
    Default: 3
  ASGMaxSize:
    Description: Maximum size of ECS Auto Scaling Group
    Type: Number
    Default: 3
  ASGDesiredCapacity:
    Description: Desired Capacity of the ECS Auto Scaling Group
    Type: Number
    Default: 3
  RollingUpdateMinInService:
    Description: Minimum instance in service during rolling update
    Type: Number
    Default: 2
  ASGEventsTopic:
    Type: String
    Description: SNS topic to notify of ASG events
  MonitoringCidr:
    Type: String
    Description: CIDR range to allow access for monitoring
    Default: ''
  Project:
    Description: Project tag
    Type: String
    MinLength: 1
    ConstraintDescription: Must be a non-empty string
  Team:
    Description: Team tag
    Type: String
    MinLength: 1
    ConstraintDescription: Must be a non-empty string
  Environment:
    Description: Environment (dev|sandbox|prod)
    Type: String
    AllowedValues: ['dev','sandbox','prod']
    Default: dev
    ConstraintDescription: Must be one of dev|sandbox|prod.

Resources:
  ECSKafka:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./ecs.yaml
      Parameters:
        KeyName: !Ref 'KeyName'
        VPCId: !Ref 'VPCId'
        VPCCidrBlock: !Ref 'VPCCidrBlock'
        Subnets: !Join [",", [!Select [0, !Ref 'Subnets'], !Select [1, !Ref 'Subnets'], !Select [2, !Ref 'Subnets']]]
        InstanceType: !Ref 'InstanceType'
        EFSFileSystemId: !ImportValue
          'Fn::Sub': '${EfsStackName}-FileSystemId'
        EFSMountPath: !Ref 'EFSMountPath'
        EFSAccessSecurityGroup: !ImportValue
          'Fn::Sub': '${EfsStackName}-FSAccessSecurityGroupID'
        ASGMinSize: !Ref 'ASGMinSize'
        ASGMaxSize: !Ref 'ASGMaxSize'
        ASGDesiredCapacity: !Ref 'ASGDesiredCapacity'
        RollingUpdateMinInService: !Ref 'RollingUpdateMinInService'
        ASGEventsTopic: !Ref 'ASGEventsTopic'
        Project: !Ref 'Project'
        Team: !Ref 'Team'
        Environment: !Ref 'Environment'
        ClusterType: kafka
        HostedZoneId: !ImportValue
          'Fn::Sub': "${HostedZoneStackName}-ZoneId"
  ECSZK:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./ecs.yaml
      Parameters:
        KeyName: !Ref 'KeyName'
        VPCId: !Ref 'VPCId'
        VPCCidrBlock: !Ref 'VPCCidrBlock'
        Subnets: !Join [",", [!Select [0, !Ref 'Subnets'], !Select [1, !Ref 'Subnets'], !Select [2, !Ref 'Subnets']]]
        InstanceType: !Ref 'InstanceType'
        EFSFileSystemId: !ImportValue
          'Fn::Sub': '${EfsStackName}-FileSystemId'
        EFSMountPath: !Ref 'EFSMountPath'
        EFSAccessSecurityGroup: !ImportValue
          'Fn::Sub': '${EfsStackName}-FSAccessSecurityGroupID'
        ASGMinSize: !Ref 'ASGMinSize'
        ASGMaxSize: !Ref 'ASGMaxSize'
        ASGDesiredCapacity: !Ref 'ASGDesiredCapacity'
        RollingUpdateMinInService: !Ref 'RollingUpdateMinInService'
        ASGEventsTopic: !Ref 'ASGEventsTopic'
        Project: !Ref 'Project'
        Team: !Ref 'Team'
        Environment: !Ref 'Environment'
        ClusterType: kafka
        HostedZoneId: !ImportValue
          'Fn::Sub': "${HostedZoneStackName}-ZoneId"          
  Zookeeper:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./zookeeper/cluster.yaml
      Parameters:
        Cluster: !GetAtt 'ECSZK.Outputs.ClusterName'
        StackName: !Ref 'AWS::StackName'
        VPCId: !Ref 'VPCId'
        EFSMountPath: !Ref 'EFSMountPath'
        Subnets: !Join [",", [!Select [0, !Ref 'Subnets'], !Select [1, !Ref 'Subnets'], !Select [2, !Ref 'Subnets']]]
        Project: !Ref 'Project'
        Team: !Ref 'Team'
        Environment: !Ref 'Environment'
        DomainName: !ImportValue
          'Fn::Sub': "${HostedZoneStackName}-ZoneName"
        MonitoringCidr: !Ref 'MonitoringCidr'
    DependsOn: 'ECSZK'
  Brokers:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./kafka/cluster.yaml
      Parameters:
        Cluster: !GetAtt 'ECSKafka.Outputs.ClusterName'
        StackName: !Ref 'AWS::StackName'
        VPCId: !Ref 'VPCId'
        EFSMountPath: !Ref 'EFSMountPath'
        Subnets: !Join [",", [!Select [0, !Ref 'Subnets'], !Select [1, !Ref 'Subnets'], !Select [2, !Ref 'Subnets']]]
        ZookeeperConnectionString: !GetAtt 'Zookeeper.Outputs.ConnectionString'
        ZookeeperSecurityGroup: !GetAtt 'Zookeeper.Outputs.ClientZKSG'
        Project: !Ref 'Project'
        Team: !Ref 'Team'
        Environment: !Ref 'Environment'
        DomainName: !ImportValue
          'Fn::Sub': "${HostedZoneStackName}-ZoneName"
        MonitoringCidr: !Ref 'MonitoringCidr'
    DependsOn: 'Zookeeper'
Outputs:
  ClusterNameZK:
    Description: A reference to the ECS ZK cluster
    Value: !GetAtt 'ECSZK.Outputs.ClusterName'
    Export:
      Name: !Sub '${AWS::StackName}-ClusterNameZK'
  ClusterNameKafka:
    Description: A reference to the ECS Kafka cluster
    Value: !GetAtt 'ECSKafka.Outputs.ClusterName'
    Export:
      Name: !Sub '${AWS::StackName}-ClusterNameKafka'
  ClientKafkaSG:
    Description: Allows Client Access to Kafka Brokers
    Value: !GetAtt 'Brokers.Outputs.ClientKafkaSG'
    Export:
      Name: !Sub '${AWS::StackName}-ClientKafkaSG'
  ClientZookeeperSG:
    Description: Allows Client Access to Zookeeper Nodes
    Value: !GetAtt 'Zookeeper.Outputs.ClientZKSG'
    Export:
      Name: !Sub '${AWS::StackName}-ClientZookeeperSG'
  ZookeeperConnectionString:
    Description: 'Comma delimited list of Zookeeper node addresses'
    Value: !GetAtt 'Zookeeper.Outputs.ConnectionString'
    Export:
      Name: !Sub '${AWS::StackName}-ZookeeperConnectionString'
  KafkaConnectionString:
    Description: 'Comma delimited list of Kafka broker addresses'
    Value: !GetAtt 'Brokers.Outputs.ConnectionString'
    Export:
      Name: !Sub '${AWS::StackName}-KafkaConnectionString'
  VpcId:
    Description: "Cluster's VPC Id"
    Value: !Ref 'VPCId'
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
