{
 "title": "Kafka ECS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus_job_name", "label": "Prometheus Job", "query": "${VAR_PROMETHEUS_JOB_NAME}" },
   {
    "name": "instance",
    "label": "Kafka Brokers",
    "query": "label_values(kafka_controller_KafkaController_Value, instance)"
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": "label_values(kafka_server_BrokerTopicMetrics_Count, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Message Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In / Second by Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",topic=~\"$topic\",name=\"MessagesInPerSec\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In / Second by Broker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",name=\"MessagesInPerSec\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Data Throughput by Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Input / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesInPerSec\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",topic=~\"$topic\",name=\"FailedFetchRequestsPerSec\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Output / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesOutPerSec\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Data Throughput by Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Input / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",name=\"BytesInPerSec\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Requests / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",topic=~\"$topic\",name=\"FailedFetchRequestsPerSec\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Output / Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$prometheus_job_name\",instance=~\"$instance\",name=\"BytesOutPerSec\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Controllers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_controller_KafkaController_Value{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"ActiveControllerCount\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"OfflinePartitionsCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_ControllerStats_Count{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"LeaderElectionRateAndTimeMs\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_ControllerStats_Count{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"UncleanLeaderElectionsPerSec\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Replica Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Partition Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"PartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR Shrinks/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_ReplicaManager_Count{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"IsrShrinksPerSec\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ISR Expands/Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_ReplicaManager_Count{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"IsrExpandsPerSec\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$prometheus_job_name\", instance=~\"$instance\", name=\"LeaderCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Heap Memory Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{job=\"$prometheus_job_name\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "init"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"$prometheus_job_name\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"$prometheus_job_name\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"$prometheus_job_name\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{job=\"$prometheus_job_name\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "init"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"$prometheus_job_name\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"$prometheus_job_name\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"$prometheus_job_name\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}