{
 "title": "Zookeeper ECS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(QuorumSize, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quorum Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "QuorumSize{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Z-node Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  NodeCount{job=\"zookeeper\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{memberType}}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  WatchCount{job=\"zookeeper\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{memberType}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(OutstandingRequests{job=\"zookeeper\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "AvgRequestLatency{job=\"zookeeper\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Zookeeper Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Max. Client Connections Per Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(MaxClientCnxnsPerHost{job=\"zookeeper\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(NumAliveConnections{job=\"zookeeper\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max. Session Timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(MaxSessionTimeout{job=\"zookeeper\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Heap Memory Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{job=\"zookeeper\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "init"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"zookeeper\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"zookeeper\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"zookeeper\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{job=\"zookeeper\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "init"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"zookeeper\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"zookeeper\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"zookeeper\", area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}