#!/bin/bash

set -e

# Specifying KAFKA_JMX_HOSTNAME in ECS causes problems because service discovery isn't available yet.
# If the JMX port is specified but the host name isn't, use the container's IP bound to the ENI
# Note: This is specifically for containers running in ECS in vpc networking mode.
if [ -n "${KAFKA_JMX_PORT}" ];
then
    export KAFKA_JMX_HOSTNAME=${KAFKA_JMX_HOSTNAME:-$(hostname -I | cut -d" " -f2)}
    echo "KAFKA_JMX_HOSTNAME: ${KAFKA_JMX_HOSTNAME}"
fi

exec "$@"