---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      # On OSX, edit /etc/hosts and add 'kafka' to 127.0.0.1
      # This is because the way broker is advertising and won't listen
      # if the host machine uses 'localhost:9092'. From the host machine
      # Use 'kafka:9092' to bootstrap.
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  # Multiple Kafka REST Proxies will not work properly for consuming
  kafka-rest-1:
    image: loyaltyone/kafka-rest:test
    container_name: kafka-rest-1
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
    ports:
      - '8082:8082'
    environment:
      APP_HOST: kafka-rest-1
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_REST_ID: 'rest-a'

