{
 "title": "Kafka - dev-kafka - US N. Virginia",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "${VAR_REGION}" },
   { "name": "stack_name", "label": "Stack Name", "query": "${VAR_STACK_NAME}" },
   { "name": "instance_name", "label": "Instance Name", "query": "${VAR_INSTANCE_NAME}" },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": "ec2_instance_attribute(us-east-1, InstanceId, { \"tag:Name\": [ \"$instance_name\" ] })"
   },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": "dev-kafka-broker1.internal.loyalty.com.,dev-kafka-broker2.internal.loyalty.com.,dev-kafka-broker3.internal.loyalty.com."
   }
  ]
 },
 "panels": [
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "MessagesInPerSec", "MetricType": "BrokerTopicMetrics" },
     "metricName": "OneMinuteRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Bytes In Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "BytesInPerSec", "MetricType": "BrokerTopicMetrics" },
     "metricName": "OneMinuteRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Bytes Out Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "BytesOutPerSec", "MetricType": "BrokerTopicMetrics" },
     "metricName": "OneMinuteRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "UnderReplicatedPartitions", "MetricType": "ReplicaManager" },
     "metricName": "Value",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "PartitionCount", "MetricType": "ReplicaManager" },
     "metricName": "Value",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "LeaderCount", "MetricType": "ReplicaManager" },
     "metricName": "Value",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "ActiveControllerCount", "MetricType": "KafkaController" },
     "metricName": "Value",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Leader Election Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "LeaderElectionRateAndTimeMs", "MetricType": "ControllerStats" },
     "metricName": "Count",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Leader Election Mean Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "LeaderElectionRateAndTimeMs", "MetricType": "ControllerStats" },
     "metricName": "MeanRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Unclean Leader Elections Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "UncleanLeaderElectionsPerSec", "MetricType": "ControllerStats" },
     "metricName": "Count",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Offline Partition Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "OfflinePartitionsCount", "MetricType": "KafkaController" },
     "metricName": "Value",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Producer Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "RequestsPerSec.Produce", "MetricType": "RequestMetrics" },
     "metricName": "MeanRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Consumer Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "RequestsPerSec.FetchConsumer", "MetricType": "RequestMetrics" },
     "metricName": "MeanRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Follower Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "RequestsPerSec.FetchFollower", "MetricType": "RequestMetrics" },
     "metricName": "MeanRate",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Producer Mean Total Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "TotalTimeMs.Produce", "MetricType": "RequestMetrics" },
     "metricName": "Mean",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Consumer Mean Time Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "TotalTimeMs.FetchConsumer", "MetricType": "RequestMetrics" },
     "metricName": "Mean",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Follower Mean Total Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name", "Metric": "TotalTimeMs.FetchFollower", "MetricType": "RequestMetrics" },
     "metricName": "Mean",
     "namespace": "Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "EC2 CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Network In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Network Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Heap Memory Usage ($host_name)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "repeat": "host_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "init",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_init",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "committed",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_committed",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "used",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_used",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "max",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_max",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage ($host_name)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "repeat": "host_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "init",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_init",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "committed",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_committed",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "used",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_used",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "max",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_max",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Root Disk Utilization ($instance_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "repeat": "instance_id",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% utilized",
     "dimensions": { "Filesystem": "/dev/nvme0n1p1", "InstanceId": "$instance_id", "MountPath": "/" },
     "metricName": "DiskSpaceUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Data Disk Utilization ($instance_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 50 },
   "repeat": "instance_id",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% utilized",
     "dimensions": { "Filesystem": "/dev/nvme2n1", "InstanceId": "$instance_id", "MountPath": "/mnt/data" },
     "metricName": "DiskSpaceUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "EC2 Memory Utilization ($instance_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 55 },
   "repeat": "instance_id",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% utilized",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "MemoryUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}