{
 "title": "Schema Registry - dev-kafka - US N. Virginia",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "${VAR_REGION}" },
   { "name": "stack_name", "label": "Stack Name", "query": "${VAR_STACK_NAME}" },
   { "name": "instance_name", "label": "Instance Name", "query": "${VAR_INSTANCE_NAME}" },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": "ec2_instance_attribute(us-east-1, InstanceId, { \"tag:Name\": [ \"$instance_name\" ] })"
   },
   { "name": "host_name", "label": "HostName", "query": "${VAR_HOST_NAME}" },
   {
    "name": "container_id",
    "label": "ContainerId",
    "query": "dimension_values($region, Schema Registry, HeapMemoryUsage_init, ContainerId)"
   },
   {
    "name": "metric_type",
    "label": "MetricType",
    "query": "dimension_values($region, Schema Registry, request-total, MetricType)"
   }
  ]
 },
 "panels": [
  { "title": "$metric_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "metric_type" },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "$metric_type" },
     "metricName": "request-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "$metric_type" },
     "metricName": "request-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Select Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "$metric_type" },
     "metricName": "select-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "I/O Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "$metric_type" },
     "metricName": "io-ratio",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "ConsumerCoordinatorMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Sync Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerCoordinatorMetrics" },
     "metricName": "sync-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Join Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerCoordinatorMetrics" },
     "metricName": "join-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Commit Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerCoordinatorMetrics" },
     "metricName": "commit-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Commit Latency Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerCoordinatorMetrics" },
     "metricName": "commit-latency-avg",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "ConsumerFetchManagerMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Records Consumed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerFetchManagerMetrics" },
     "metricName": "records-consumed-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Records Consumed Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerFetchManagerMetrics" },
     "metricName": "records-consumed-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Bytes Consumed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerFetchManagerMetrics" },
     "metricName": "bytes-consumed-total",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ConsumerFetchManagerMetrics" },
     "metricName": "bytes-consumed-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "ProducerTopicMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Byte Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ProducerTopicMetrics" },
     "metricName": "byte-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Record Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ProducerTopicMetrics" },
     "metricName": "record-error-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Record Retry Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ProducerTopicMetrics" },
     "metricName": "record-retry-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Record Send Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "ProducerTopicMetrics" },
     "metricName": "record-send-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "JerseyMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "JerseyMetrics" },
     "metricName": "request-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "JerseyMetrics" },
     "metricName": "response-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{ContainerId}}",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name", "MetricType": "JerseyMetrics" },
     "metricName": "request-error-rate",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Root Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "Filesystem": "/dev/nvme0n1p1", "InstanceId": "$instance_id", "MountPath": "/" },
     "metricName": "DiskSpaceUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Data Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "Filesystem": "/dev/nvme2n1", "InstanceId": "$instance_id", "MountPath": "/mnt/data" },
     "metricName": "DiskSpaceUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "MemoryUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "JVM Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Heap Memory Usage ($container_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
   "repeat": "container_id",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "init",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_init",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "committed",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_committed",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "used",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_used",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "max",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_max",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "JVM Non-Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Non-Heap Memory Usage ($container_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 48 },
   "repeat": "container_id",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "init",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_init",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "committed",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_committed",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "used",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_used",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "max",
     "dimensions": { "ContainerId": "$container_id", "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_max",
     "namespace": "Schema Registry",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}