{
 "title": "Zookeeper - dev-kafka - US N. Virginia",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "${VAR_REGION}" },
   { "name": "stack_name", "label": "Stack Name", "query": "${VAR_STACK_NAME}" },
   { "name": "instance_name", "label": "Instance Name", "query": "${VAR_INSTANCE_NAME}" },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": "ec2_instance_attribute(us-east-1, InstanceId, { \"tag:Name\": [ \"$instance_name\" ] })"
   },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": "dev-kafka-zk1.internal.loyalty.com.,dev-kafka-zk2.internal.loyalty.com.,dev-kafka-zk3.internal.loyalty.com."
   }
  ]
 },
 "panels": [
  {
   "title": "Quorum Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "QuorumSize",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "OutstandingRequests",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "AvgRequestLatency",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Max Client Connections Per Host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "MaxClientCnxnsPerHost",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Max Client Connections Per Host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "MaxClientCnxnsPerHost",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Max Session Timeout",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{HostName}}",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "MaxSessionTimeout",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "EC2 CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Network In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Network Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Heap Memory Usage ($host_name)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "host_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "init",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_init",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "committed",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_committed",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "used",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_used",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "max",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "HeapMemoryUsage_max",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage ($host_name)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "repeat": "host_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "init",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_init",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "committed",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_committed",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "used",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_used",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "max",
     "dimensions": { "HostName": "$host_name" },
     "metricName": "NonHeapMemoryUsage_max",
     "namespace": "Zookeeper",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Root Disk Utilization ($instance_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "repeat": "instance_id",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% utilized",
     "dimensions": { "Filesystem": "/dev/nvme0n1p1", "InstanceId": "$instance_id", "MountPath": "/" },
     "metricName": "DiskSpaceUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EC2 Data Disk Utilization ($instance_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "repeat": "instance_id",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% utilized",
     "dimensions": { "Filesystem": "/dev/nvme2n1", "InstanceId": "$instance_id", "MountPath": "/mnt/data" },
     "metricName": "DiskSpaceUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "EC2 Memory Utilization ($instance_id)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "repeat": "instance_id",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% utilized",
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "MemoryUtilization",
     "namespace": "System/Linux",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}