#!/bin/bash

set -e

if [ -n "${KAFKA_JMX_PORT}" ] || [ -n "${KAFKA_JMX_HOSTNAME}" ] || [ -n "${KAFKA_JMX_OPTS}" ];
then
    # JMX agent complains about malformed URLs and is not able to resolve ECS container
    # short hostnames. This will take care of the problem.
    echo "127.0.0.1     $HOSTNAME" | tee -a /etc/hosts
fi
echo "KAFKA_JMX_HOSTNAME: ${KAFKA_JMX_HOSTNAME}"
echo "KAFKA_JMX_PORT: ${KAFKA_JMX_PORT}"

if [ -z "${KAFKA_BROKER_RACK}" ];
then
    # Assume AWS environment and use the AZ as the rack name. This will help with spreading replicas of the same
    # partition across different AZs.
    export KAFKA_BROKER_RACK=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)
fi
echo "KAFKA_BROKER_RACK: ${KAFKA_BROKER_RACK}"

exec "$@"