---
AWSTemplateFormatVersion: '2010-09-09'

Description: Kafka Cluster

Parameters:
  Cluster:
    Description: ECS Cluster
    Type: String
  StackName:
    Description: The Parent Stack Name
    Type: String
  VPCId:
    Description: Choose which VPC this cluster should be deployed to
    Type: AWS::EC2::VPC::Id
  EFSMountPath:
    Description: Path at which to create the volume mount for EFS
    Type: String
    Default: /mnt/efs
  Subnets:
    Description: Choose three private subnets this cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>
  ClientPort:
    Description: Kafka client port
    Type: Number
    Default: 9092
  ZookeeperConnectionString:
    Description: Connection string for Zookeeper Cluster
    Type: String
  ZookeeperSecurityGroup:
    Description: Security Group to allow access to ZK
    Type: String
  Cpu:
    Description: Amount of CPU to reserve
    Type: Number
    Default: 1024
  Memory:
    Description: Amount of Memory to reserve
    Type: Number
    Default: 4096
  Project:
    Description: Project tag
    Type: String
    MinLength: 1
    ConstraintDescription: Must be a non-empty string
  Team:
    Description: Team tag
    Type: String
    MinLength: 1
    ConstraintDescription: Must be a non-empty string
  Environment:
    Description: Environment (dev|sandbox|prod)
    Type: String
    AllowedValues: ['dev','sandbox','prod']
    Default: dev
    ConstraintDescription: Must be one of dev|sandbox|prod.
  DomainName:
    Description: The domain name for Kafka brokers
    Type: String
  PrometheusJmxExporterPort:
    Description: The JMX port to use for metric collection
    Type: Number
    Default: 9404
  MonitoringCidr:
    Type: String
    Description: CIDR range to allow access for monitoring
    Default: ''

Conditions:
  AllowMonitoringCidr: !Not [!Equals [!Ref 'MonitoringCidr', '']]

Resources:
  BrokersLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '${StackName}/kafka'
      RetentionInDays: 1
  ClientKafkaSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${AWS::StackName}-client-kafka-sg'
      GroupDescription: Allows Client Access to Kafka Brokers
      VpcId: !Ref 'VPCId'
      Tags:
        - Key: Project
          Value: !Ref 'Project'
        - Key: Team
          Value: !Ref 'Team'
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: Component
          Value: kafka
      SecurityGroupEgress:
        IpProtocol: -1
        CidrIp: "0.0.0.0/0"
  InternalKafkaSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${AWS::StackName}-internal-kafka-sg'
      GroupDescription: Allows Internal Access to Zookeeper Nodes
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref 'ClientKafkaSG'
          IpProtocol: tcp
          FromPort: !Ref 'ClientPort'
          ToPort: !Ref 'ClientPort'
      VpcId: !Ref 'VPCId'
      Tags:
        - Key: Project
          Value: !Ref 'Project'
        - Key: Team
          Value: !Ref 'Team'
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: Component
          Value: zookeeper
      SecurityGroupEgress:
        IpProtocol: -1
        CidrIp: "0.0.0.0/0"
    DependsOn: 'ClientKafkaSG'
  InternalKafkaSGIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      FromPort: !Ref 'ClientPort'
      ToPort: !Ref 'ClientPort'
      GroupId: !Ref 'InternalKafkaSG'
      SourceSecurityGroupId: !Ref 'InternalKafkaSG'
    DependsOn: 'InternalKafkaSG'
  InternalKafkaSGIngressPrometheusExporterRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Condition: AllowMonitoringCidr
    Properties:
      IpProtocol: tcp
      FromPort: !Ref 'PrometheusJmxExporterPort'
      ToPort: !Ref 'PrometheusJmxExporterPort'
      GroupId: !Ref 'InternalKafkaSG'
      CidrIp: !Ref 'MonitoringCidr'
  Broker1:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./service.yaml
      Parameters:
        Cluster: !Ref 'Cluster'
        StackName: !Ref 'StackName'
        Cpu: !Ref 'Cpu'
        Memory: !Ref 'Memory'
        EFSMountPath: !Ref 'EFSMountPath'
        ZookeeperConnectionString: !Ref 'ZookeeperConnectionString'
        ZookeeperSecurityGroup: !Ref 'ZookeeperSecurityGroup'
        BrokerId: 1
        BrokerName: !Sub '${StackName}-broker'
        DomainName: !Ref 'DomainName'
        ClientPort: !Ref 'ClientPort'
        LogGroup: !Ref 'BrokersLogGroup'
        SecurityGroup: !Ref 'InternalKafkaSG'
        SubnetId: !Select [ 0, !Ref 'Subnets' ]
        PrometheusJmxExporterPort: !Ref 'PrometheusJmxExporterPort'
    DependsOn: ['BrokersLogGroup', 'InternalKafkaSG']
  Broker2:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./service.yaml
      Parameters:
        Cluster: !Ref 'Cluster'
        StackName: !Ref 'StackName'
        Cpu: !Ref 'Cpu'
        Memory: !Ref 'Memory'
        EFSMountPath: !Ref 'EFSMountPath'
        ZookeeperConnectionString: !Ref 'ZookeeperConnectionString'
        ZookeeperSecurityGroup: !Ref 'ZookeeperSecurityGroup'
        BrokerId: 2
        BrokerName: !Sub '${StackName}-broker'
        DomainName: !Ref 'DomainName'
        ClientPort: !Ref 'ClientPort'
        LogGroup: !Ref 'BrokersLogGroup'
        SecurityGroup: !Ref 'InternalKafkaSG'
        SubnetId: !Select [ 1, !Ref 'Subnets' ]
        PrometheusJmxExporterPort: !Ref 'PrometheusJmxExporterPort'
    DependsOn: ['BrokersLogGroup', 'InternalKafkaSG', 'Broker1']
  Broker3:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./service.yaml
      Parameters:
        Cluster: !Ref 'Cluster'
        StackName: !Ref 'StackName'
        Cpu: !Ref 'Cpu'
        Memory: !Ref 'Memory'
        EFSMountPath: !Ref 'EFSMountPath'
        ZookeeperConnectionString: !Ref 'ZookeeperConnectionString'
        ZookeeperSecurityGroup: !Ref 'ZookeeperSecurityGroup'
        BrokerId: 3
        BrokerName: !Sub '${StackName}-broker'
        DomainName: !Ref 'DomainName'
        ClientPort: !Ref 'ClientPort'
        LogGroup: !Ref 'BrokersLogGroup'
        SecurityGroup: !Ref 'InternalKafkaSG'
        SubnetId: !Select [ 2, !Ref 'Subnets' ]
        PrometheusJmxExporterPort: !Ref 'PrometheusJmxExporterPort'
    DependsOn: ['BrokersLogGroup', 'InternalKafkaSG', 'Broker2']

Outputs:
  ClientKafkaSG:
    Description: Allows Client Access to Kafka Brokers
    Value: !Ref 'ClientKafkaSG'
  ConnectionString:
    Description: Connection string to connect to kafka brokers
    Value: !Sub
      - '${Broker1},${Broker2},${Broker3}'
      - Broker1: !GetAtt 'Broker1.Outputs.ConnectionString'
        Broker2: !GetAtt 'Broker2.Outputs.ConnectionString'
        Broker3: !GetAtt 'Broker3.Outputs.ConnectionString'
